app:
  name: "profile"
  graceful_shutdown_timeout_seconds: 10

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

postgres:
  username: "profile-owner"
  host: "profile-postgres"
  port: "5432"
  db_name: "profile"
  ssl_mode: "disable"
  migrations_folder: "migrations"

s3:
  addr: "minio:9000"
  bucket_name: "swiply"
  access_key: 9a301bda16acb36efcf08cb73ad60ef8
  secure: false

user:
  addr: "user:84"

notification:
  addr: "notification:84"