# Generated by Django 5.0.4 on 2024-05-07 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('other_email', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('name', models.TextField()),
                ('birthdate', models.TextField()),
                ('gender', models.TextField()),
                ('city', models.TextField()),
                ('subscription', models.TextField()),
                ('work', models.TextField()),
                ('education', models.TextField()),
                ('description', models.TextField()),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('isBlocked', models.BooleanField()),
                ('photoes', models.ImageField(blank=True, default='books2.jpg', upload_to='')),
            ],
        ),
    ]
