app:
  name: "event"
  graceful_shutdown_timeout_seconds: 10

jaeger:
  addr: "opentelemetry-collector.otel-collector.svc.cluster.local:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

chat:
  addr: "chat:84"

postgres:
  username: "event-owner"
  host: "c-c9qk6bb4fb5n0j9pu5rr.rw.mdb.yandexcloud.net"
  port: "6432"
  db_name: "event"
  ssl_mode: "allow"
  migrations_folder: "migrations"

s3:
  addr: "storage.yandexcloud.net"
  bucket_name: "swiply"
  access_key: YCAJED9kjBxxO8bHOrkON7TL1
  secure: true
