/swiply.chat.Chat/SendMessage:
  user: true
  s2s: false

/swiply.chat.Chat/GetNextMessages:
  user: true
  s2s: false

/swiply.chat.Chat/GetPreviousMessages:
  user: true
  s2s: false

/swiply.chat.Chat/GetChats:
  user: true
  s2s: false

/swiply.chat.Chat/LeaveChat:
  user: true
  s2s: false

/swiply.chat.Chat/CreateChat:
  user: true
  s2s: true
  authorized:
    - event

/swiply.chat.Chat/AddChatMembers:
  user: true
  s2s: true
  authorized:
    - event
