app:
  name: "chat"
  graceful_shutdown_timeout_seconds: 10
  num_of_message_sender_workers: 10

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

redis:
  addr: "chat-redis:6379"

postgres:
  username: "chat-owner"
  host: "chat-postgres"
  port: "5432"
  db_name: "chat"
  ssl_mode: "disable"
  migrations_folder: "migrations"
