app:
  name: "oracle"
  graceful_shutdown_timeout_seconds: 10

grpc:
  addr: "0.0.0.0:84"

postgres:
  username: "recommendation-owner"
  host: "recommendation-postgres"
  port: "5432"
  db_name: "recommendation"
  ssl_mode: "disable"
