app:
  name: "user"
  graceful_shutdown_timeout_seconds: 10
  auth_code_ttl_minutes: 15
  auth_code_sending_min_retry_time_minutes: 2
  access_token_ttl_minutes: 10
  refresh_token_ttl_hours: 168

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

mailer:
  smtp_addr: "smtp.mail.ru:25"
  sender_email: "swiply-no-reply@inbox.ru"
  send_timeout_seconds: 5
  after_send_pause_seconds: 1

redis:
  addr: "user-redis:6379"