app:
  name: "notification"
  graceful_shutdown_timeout_seconds: 10
  topic: "Swiply"

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

postgres:
  username: "notification-owner"
  host: "notification-postgres"
  port: "5432"
  db_name: "notification"
  ssl_mode: "disable"
  migrations_folder: "migrations"

apns:
  signing_key_path: "secrets/token_signing_pk.p8"
