# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oracle.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coracle.proto\x12\rswiply.oracle\"\x15\n\x13RetrainLFMv1Request\"\'\n\x14RetrainLFMv1Response\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\'\n\x14GetTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"S\n\x15GetTaskStatusResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.swiply.oracle.TaskStatus\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t*B\n\nTaskStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\xbd\x01\n\x06Oracle\x12W\n\x0cRetrainLFMv1\x12\".swiply.oracle.RetrainLFMv1Request\x1a#.swiply.oracle.RetrainLFMv1Response\x12Z\n\rGetTaskStatus\x12#.swiply.oracle.GetTaskStatusRequest\x1a$.swiply.oracle.GetTaskStatusResponseB-Z+github.com/the-swiply/oracle/pkg/api/oracleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oracle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/the-swiply/oracle/pkg/api/oracle'
  _globals['_TASKSTATUS']._serialized_start=221
  _globals['_TASKSTATUS']._serialized_end=287
  _globals['_RETRAINLFMV1REQUEST']._serialized_start=31
  _globals['_RETRAINLFMV1REQUEST']._serialized_end=52
  _globals['_RETRAINLFMV1RESPONSE']._serialized_start=54
  _globals['_RETRAINLFMV1RESPONSE']._serialized_end=93
  _globals['_GETTASKSTATUSREQUEST']._serialized_start=95
  _globals['_GETTASKSTATUSREQUEST']._serialized_end=134
  _globals['_GETTASKSTATUSRESPONSE']._serialized_start=136
  _globals['_GETTASKSTATUSRESPONSE']._serialized_end=219
  _globals['_ORACLE']._serialized_start=290
  _globals['_ORACLE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
