// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/oracle.proto

package oracle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OracleClient is the client API for Oracle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OracleClient interface {
	RetrainLFMv1(ctx context.Context, in *RetrainLFMv1Request, opts ...grpc.CallOption) (*RetrainLFMv1Response, error)
	GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
}

type oracleClient struct {
	cc grpc.ClientConnInterface
}

func NewOracleClient(cc grpc.ClientConnInterface) OracleClient {
	return &oracleClient{cc}
}

func (c *oracleClient) RetrainLFMv1(ctx context.Context, in *RetrainLFMv1Request, opts ...grpc.CallOption) (*RetrainLFMv1Response, error) {
	out := new(RetrainLFMv1Response)
	err := c.cc.Invoke(ctx, "/swiply.oracle.Oracle/RetrainLFMv1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oracleClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	out := new(GetTaskStatusResponse)
	err := c.cc.Invoke(ctx, "/swiply.oracle.Oracle/GetTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OracleServer is the server API for Oracle service.
// All implementations must embed UnimplementedOracleServer
// for forward compatibility
type OracleServer interface {
	RetrainLFMv1(context.Context, *RetrainLFMv1Request) (*RetrainLFMv1Response, error)
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error)
	mustEmbedUnimplementedOracleServer()
}

// UnimplementedOracleServer must be embedded to have forward compatible implementations.
type UnimplementedOracleServer struct {
}

func (UnimplementedOracleServer) RetrainLFMv1(context.Context, *RetrainLFMv1Request) (*RetrainLFMv1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrainLFMv1 not implemented")
}
func (UnimplementedOracleServer) GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedOracleServer) mustEmbedUnimplementedOracleServer() {}

// UnsafeOracleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OracleServer will
// result in compilation errors.
type UnsafeOracleServer interface {
	mustEmbedUnimplementedOracleServer()
}

func RegisterOracleServer(s grpc.ServiceRegistrar, srv OracleServer) {
	s.RegisterService(&Oracle_ServiceDesc, srv)
}

func _Oracle_RetrainLFMv1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrainLFMv1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleServer).RetrainLFMv1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swiply.oracle.Oracle/RetrainLFMv1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleServer).RetrainLFMv1(ctx, req.(*RetrainLFMv1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oracle_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swiply.oracle.Oracle/GetTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleServer).GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oracle_ServiceDesc is the grpc.ServiceDesc for Oracle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oracle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swiply.oracle.Oracle",
	HandlerType: (*OracleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrainLFMv1",
			Handler:    _Oracle_RetrainLFMv1_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _Oracle_GetTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/oracle.proto",
}
