// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/oracle.proto

package oracle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_UNKNOWN     TaskStatus = 0
	TaskStatus_IN_PROGRESS TaskStatus = 1
	TaskStatus_SUCCESS     TaskStatus = 2
	TaskStatus_ERROR       TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "IN_PROGRESS",
		2: "SUCCESS",
		3: "ERROR",
	}
	TaskStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"IN_PROGRESS": 1,
		"SUCCESS":     2,
		"ERROR":       3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_oracle_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_oracle_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_oracle_proto_rawDescGZIP(), []int{0}
}

type RetrainLFMv1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetrainLFMv1Request) Reset() {
	*x = RetrainLFMv1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_oracle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrainLFMv1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainLFMv1Request) ProtoMessage() {}

func (x *RetrainLFMv1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_oracle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainLFMv1Request.ProtoReflect.Descriptor instead.
func (*RetrainLFMv1Request) Descriptor() ([]byte, []int) {
	return file_api_oracle_proto_rawDescGZIP(), []int{0}
}

type RetrainLFMv1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *RetrainLFMv1Response) Reset() {
	*x = RetrainLFMv1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_oracle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrainLFMv1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainLFMv1Response) ProtoMessage() {}

func (x *RetrainLFMv1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_oracle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainLFMv1Response.ProtoReflect.Descriptor instead.
func (*RetrainLFMv1Response) Descriptor() ([]byte, []int) {
	return file_api_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *RetrainLFMv1Response) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_oracle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oracle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  TaskStatus `protobuf:"varint,1,opt,name=status,proto3,enum=swiply.oracle.TaskStatus" json:"status,omitempty"`
	Details string     `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_oracle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oracle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskStatusResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_UNKNOWN
}

func (x *GetTaskStatusResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_api_oracle_proto protoreflect.FileDescriptor

var file_api_oracle_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x46, 0x4d, 0x76,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x4c, 0x46, 0x4d, 0x76, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x2a, 0x42, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49,
	0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x32, 0xbd, 0x01, 0x0a, 0x06, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x12,
	0x57, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x46, 0x4d, 0x76, 0x31, 0x12,
	0x22, 0x2e, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x46, 0x4d, 0x76, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x46, 0x4d, 0x76, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x2e, 0x73, 0x77, 0x69, 0x70,
	0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x2d, 0x73, 0x77, 0x69, 0x70, 0x6c, 0x79, 0x2f, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_oracle_proto_rawDescOnce sync.Once
	file_api_oracle_proto_rawDescData = file_api_oracle_proto_rawDesc
)

func file_api_oracle_proto_rawDescGZIP() []byte {
	file_api_oracle_proto_rawDescOnce.Do(func() {
		file_api_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_oracle_proto_rawDescData)
	})
	return file_api_oracle_proto_rawDescData
}

var file_api_oracle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_oracle_proto_goTypes = []interface{}{
	(TaskStatus)(0),               // 0: swiply.oracle.TaskStatus
	(*RetrainLFMv1Request)(nil),   // 1: swiply.oracle.RetrainLFMv1Request
	(*RetrainLFMv1Response)(nil),  // 2: swiply.oracle.RetrainLFMv1Response
	(*GetTaskStatusRequest)(nil),  // 3: swiply.oracle.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil), // 4: swiply.oracle.GetTaskStatusResponse
}
var file_api_oracle_proto_depIdxs = []int32{
	0, // 0: swiply.oracle.GetTaskStatusResponse.status:type_name -> swiply.oracle.TaskStatus
	1, // 1: swiply.oracle.Oracle.RetrainLFMv1:input_type -> swiply.oracle.RetrainLFMv1Request
	3, // 2: swiply.oracle.Oracle.GetTaskStatus:input_type -> swiply.oracle.GetTaskStatusRequest
	2, // 3: swiply.oracle.Oracle.RetrainLFMv1:output_type -> swiply.oracle.RetrainLFMv1Response
	4, // 4: swiply.oracle.Oracle.GetTaskStatus:output_type -> swiply.oracle.GetTaskStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_oracle_proto_init() }
func file_api_oracle_proto_init() {
	if File_api_oracle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_oracle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrainLFMv1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_oracle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrainLFMv1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_oracle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_oracle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_oracle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_oracle_proto_goTypes,
		DependencyIndexes: file_api_oracle_proto_depIdxs,
		EnumInfos:         file_api_oracle_proto_enumTypes,
		MessageInfos:      file_api_oracle_proto_msgTypes,
	}.Build()
	File_api_oracle_proto = out.File
	file_api_oracle_proto_rawDesc = nil
	file_api_oracle_proto_goTypes = nil
	file_api_oracle_proto_depIdxs = nil
}
